### ISSUE TITLE
[SOURCE] ravenscans.com

### ISSUE THREAD

**Issue by Yucked** [Yucked/Grimoire#9]
List: https://ravenscans.com/manga/list-mode/

**Comment by Yucked** [comment]
Null ref thrown when parsing text-mode page

```cs
 Unhandled exception rendering component: Object reference not set to an instance of an object.
      System.NullReferenceException: Object reference not set to an instance of an object.
         at Grimoire.Sources.Helpers.WordPressHelper.GetMangaAsync(String url) in C:\Users\Yucked\Desktop\Grimoire\Grimoire.Sources\Helpers\WordPressHelper.cs:line 48
         at Grimoire.Sources.Helpers.WordPressHelper.GetMangasAsync() in C:\Users\Yucked\Desktop\Grimoire\Grimoire.Sources\Helpers\WordPressHelper.cs:line 41
         at Grimoire.Web.Handlers.CacheHandler.GetMangasAsync(String sourceId, Boolean refresh) in C:\Users\Yucked\Desktop\Grimoire\Grimoire.Web\Handlers\CacheHandler.cs:line 84
         at Grimoire.Web.Pages.SourcePage.OnInitializedAsync() in C:\Users\Yucked\Desktop\Grimoire\Grimoire.Web\Pages\SourcePage.razor:line 81
         at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)

```
